<h1 style="text-align: center;"><a title="Data Science-AIMS-Cmr-2021-22">Chapter 1: Working with Time Data</h1>

**Instructor:**

* Rockefeller

Time series data lies at the heart of numerous practical applications across various fields, underlining its immense importance. By capturing data points at successive time intervals, time series analysis enables us to uncover valuable insights, observe patterns, and make accurate forecasts. It finds practical application in diverse domains such as **finance, economics, weather forecasting, stock market analysis, demand forecasting, anomaly detection, and predictive maintenance**.

Whether we aim to 

* Predict future stock prices in **Douala Stock Exchange** in Cameroon, 

* Understand consumer behavior over time on the  **Takealot.com** E-commence website in Zimbabwe, 

* Monitor sensor readings for spotting anomalies in the Engineering Division of **DAL Group** in Sudan,

* Forecast seasonal trends of fashion accessories designed by **LE Creation** in Ivory Coast,

a solid grasp of time series analysis proves indispensable. So, let's delve into the fascinating world of time series and explore the tools and techniques that enable us to extract meaningful information from temporal data.

**Learning Objectives:**

* Get the standard definitions of time series,
* Perform time series analysis,
* Identify the important components to consider in time series data.
* And the Examples of time series to make your understanding concrete.

## Working with Time in Pandas

One of the best reasons to use Pandas is its capability to identify and handle **time** and **date** variables in the data values we work on. In the previous chapters, we saw some simple cases where the data was nothing more than string labels and numeric values. 

In reality, data can have many formats, and dates and times are almost omnipresent. In fact, in the collection of
data, in their sampling, dates and times are introduced. 

It is this type of value that is indispensable for carrying out significant statistics and,
therefore, in the analysis of the data, it is essential that the tools are able to
recognize and use them. The Pandas library manages this type of data based on the following two
specific concepts:

1. Date Times
2. Time deltas

### Date Times

Date Times represent the concept of date and time, typically indicated as a certain instant. Working with data, we often encounter dates and times expressed as strings in various formats. For example, the order of years, months, and days (and sometimes hours, minutes, and seconds) can differ significantly based on the country of origin.

The  African Continent for instance, has six time zones which are (and can vary) 

* Mauritius and Seychelles Time (UTC/GMT+4),  
* East Africa Time (UTC/GMT+3),  
* Central Africa Time (UTC/GMT+2), 
* West Africa Time (UTC/GMT+1),  
* Greenwich Mean Time (UTC/GMT), 
* Cape Verde Time (UTC-1).


Different specificaitions could apply to the way time series are represented:


* These values can be numeric (e.g., **11** for November) or literal (e.g., **Nov**). 
* Years can have four or two digits (e.g., **2021** or **21**). 
* The separator character between values varies widely (`'-', '/', or ':'`, etc.). 


Parsing these values accurately is challenging, hence the need of a powerful library, to simplify those processes for data analysts. It uses the `datetime` module and provides the `Timestamp` class, which efficiently handles Date Time. Its constructor accepts a string and converts it to `datetime64`, a specific Pandas data type representing the corresponding nanosecond value. This precise value is ideal for scientific applications involving short time spans.

Let’s write a series of examples on recognizing and converting dates with
the `Timestamp()` constructor, as follows:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
pd.Timestamp('2021-11-30')

Timestamp('2021-11-30 00:00:00')

In [5]:
pd.Timestamp('2021-Nov-30')

Timestamp('2021-11-30 00:00:00')

In [4]:
pd.Timestamp('2021/11/30')

Timestamp('2021-11-30 00:00:00')

In [6]:
pd.Timestamp('2022 March 14'  )

Timestamp('2022-03-14 00:00:00')

In [7]:
pd.to_datetime('2023#05#03' , 
               format = '%Y#%d#%m' )

Timestamp('2023-03-05 00:00:00')

In [8]:
pd.to_datetime('2024-05-09' , 
               format = '%Y-%d-%m' )

Timestamp('2024-09-05 00:00:00')

In [9]:
pd.to_datetime('2024-05-09' , 
               format = '%Y-%m-%d' )

Timestamp('2024-05-09 00:00:00')

In [9]:
pd.to_datetime('2023vanessa05vanessa03' , 
               format = '%Yvanessa%dvanessa%m' )

Timestamp('2023-03-05 00:00:00')

It can deduced from the preceding examples that regardless of the format
type, the `Timestamp()` constructor is able to recognize that it is the same
date. This constructor is also able to work on numeric formats and not only with
strings. In this case, each argument will correspond in the order of years,
months, days, hours, minutes, and seconds, as shown as follows:

In [10]:
pd.Timestamp(2021,11,30,11,0,35)

Timestamp('2021-11-30 11:00:35')

The Pandas library provides us with the `to_datetime()` function which accepts,
as an argument, a series of objects which will then be converted into DateTime values.

In [11]:
df = pd.DataFrame({'year': [2019, 2020, 2021], 
                   'month': [10, 6, 4], 
                   'day': [15, 10, 20], 
                  'hour': [12 , 15 , 49]})
df

   year  month  day  hour
0  2019     10   15    12
1  2020      6   10    15
2  2021      4   20    49

It can be converted to DateTime values using the `to_datetime()` function,
as shown as follows:

In [12]:
t_stamp = pd.to_datetime(df)
t_stamp

0   2019-10-15 12:00:00
1   2020-06-10 15:00:00
2   2021-04-22 01:00:00
dtype: datetime64[ns]

In [13]:
df['Date'] =  t_stamp
df

   year  month  day  hour                Date
0  2019     10   15    12 2019-10-15 12:00:00
1  2020      6   10    15 2020-06-10 15:00:00
2  2021      4   20    49 2021-04-22 01:00:00

In [14]:
t_stamp.dt.weekday

0    1
1    2
2    3
dtype: int32

In [15]:
t_stamp.dt.day_name()

0      Tuesday
1    Wednesday
2     Thursday
dtype: object

As we can see, the function has converted a DataFrame into a Series of
`datetime64` values.

Another possibility is, for example, that of converting strings that describe a
date and a time but their format is too intelligible for the constructor. In
fact, the `to_datetime()` function allows you to add as an optional
parameter, the format in which you can specify the particular formatting
that follows the string by means of indicators (called format codes, as for
example, `%S` to indicate the seconds) and, thus, be able to parse. Also, by
adding the optional errors parameter with the value `raise`, you will get an
error message whenever the `to_datetime()` function fails to parse the
string in a datetime64 value, as shown as follows:

In [16]:
t = pd.to_datetime('2021 USA 10--<-12', format='%Y USA %d--<-%m',
                   errors='coerce')
t

Timestamp('2021-12-10 00:00:00')

In [17]:
t = pd.to_datetime('2021 USA 10--<-12', format='%Y USA %d %m',
                   errors='ignore')
t

/tmp/ipykernel_11071/2944119019.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  t = pd.to_datetime('2021 USA 10--<-12', format='%Y USA %d %m',

'2021 USA 10--<-12'

In [18]:
pd.to_datetime?

Signature:
pd.to_datetime(
    arg: 'DatetimeScalarOrArrayConvertible | DictConvertible',
    errors: 'DateTimeErrorChoices' = 'raise',
    dayfirst: 'bool' = False,
    yearfirst: 'bool' = False,
    utc: 'bool' = False,
    format: 'str | None' = None,
    exact: 'bool | lib.NoDefault' = <no_default>,
    unit: 'str | None' = None,
    infer_datetime_format: 'lib.NoDefault | bool' = <no_default>,
    origin: 'str' = 'unix',
    cache: 'bool' = True,
) -> 'DatetimeIndex | Series | DatetimeScalar | NaTType | None'
Docstring:
Convert argument to datetime.

This function converts a scalar, array-like, :class:`Series` or
:class:`DataFrame`/dict-like to a pandas datetime object.

Parameters
----------
arg : int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like
    The object to convert to a datetime. If a :class:`DataFrame` is provided, the
    method expects minimally the following columns: :const:`"year"`,
    :const:`"month"`, :const:`"day"`. The column "year"
    must be specified in 4-digit format.
errors : {'ignore', 'raise', 'coerce'}, default 'raise'
    - If :const:`'raise'`, then invalid parsing will raise an exception.
    - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`.
    - If :const:`'ignore'`, then invalid parsing will return the input.
dayfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.
    If :const:`True`, parses dates with the day first, e.g. :const:`"10/11/12"`
    is parsed as :const:`2012-11-10`.

    .. warning::

        ``dayfirst=True`` is not strict, but will prefer to parse
        with day first.

yearfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.

    - If :const:`True` parses dates with the year first, e.g.
      :const:`"10/11/12"` is parsed as :const:`2010-11-12`.
    - If both `dayfirst` and `yearfirst` are :const:`True`, `yearfirst` is
      preceded (same as :mod:`dateutil`).

    .. warning::

        ``yearfirst=True`` is not strict, but will prefer to parse
        with year first.

utc : bool, default False
    Control timezone-related parsing, localization and conversion.

    - If :const:`True`, the function *always* returns a timezone-aware
      UTC-localized :class:`Timestamp`, :class:`Series` or
      :class:`DatetimeIndex`. To do this, timezone-naive inputs are
      *localized* as UTC, while timezone-aware inputs are *converted* to UTC.

    - If :const:`False` (default), inputs will not be coerced to UTC.
      Timezone-naive inputs will remain naive, while timezone-aware ones
      will keep their time offsets. Limitations exist for mixed
      offsets (typically, daylight savings), see :ref:`Examples
      <to_datetime_tz_examples>` section for details.

    .. warning::

        In a future version of pandas, parsing datetimes with mixed time
        zones will raise an error unless `utc=True`.
        Please specify `utc=True` to opt in to the new behaviour
        and silence this warning. To create a `Series` with mixed offsets and
        `object` dtype, please use `apply` and `datetime.datetime.strptime`.

    See also: pandas general documentation about `timezone conversion and
    localization
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
    #time-zone-handling>`_.

format : str, default None
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. note::

        If a :class:`DataFrame` is passed, then `format` has no effect.

exact : bool, default True
    Control how `format` is used:

    - If :const:`True`, require an exact `format` match.
    - If :const:`False`, allow the `format` to match anywhere in the target
      string.

    Cannot be used alongside ``format='ISO8601'`` or ``format='mixed'``.
unit : str, default 'ns'
    The unit of the arg (D,s,ms,us,ns) denote the unit, which is an
    integer or float number. This will be based off the origin.
    Example, with ``unit='ms'`` and ``origin='unix'``, this would calculate
    the number of milliseconds to the unix epoch start.
infer_datetime_format : bool, default False
    If :const:`True` and no `format` is given, attempt to infer the format
    of the datetime strings based on the first non-NaN element,
    and if it can be inferred, switch to a faster method of parsing them.
    In some cases this can increase the parsing speed by ~5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has
        no effect.

origin : scalar, default 'unix'
    Define the reference date. The numeric values would be parsed as number
    of units (defined by `unit`) since this reference date.

    - If :const:`'unix'` (or POSIX) time; origin is set to 1970-01-01.
    - If :const:`'julian'`, unit must be :const:`'D'`, and origin is set to
      beginning of Julian Calendar. Julian day number :const:`0` is assigned
      to the day starting at noon on January 1, 4713 BC.
    - If Timestamp convertible (Timestamp, dt.datetime, np.datetimt64 or date
      string), origin is set to Timestamp identified by origin.
    - If a float or integer, origin is the difference
      (in units determined by the ``unit`` argument) relative to 1970-01-01.
cache : bool, default True
    If :const:`True`, use a cache of unique, converted dates to apply the
    datetime conversion. May produce significant speed-up when parsing
    duplicate date strings, especially ones with timezone offsets. The cache
    is only used when there are at least 50 values. The presence of
    out-of-bounds values will render the cache unusable and may slow down
    parsing.

Returns
-------
datetime
    If parsing succeeded.
    Return type depends on input (types in parenthesis correspond to
    fallback in case of unsuccessful timezone or out-of-range timestamp
    parsing):

    - scalar: :class:`Timestamp` (or :class:`datetime.datetime`)
    - array-like: :class:`DatetimeIndex` (or :class:`Series` with
      :class:`object` dtype containing :class:`datetime.datetime`)
    - Series: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)
    - DataFrame: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)

Raises
------
ParserError
    When parsing a date from string fails.
ValueError
    When another datetime conversion error happens. For example when one
    of 'year', 'month', day' columns is missing in a :class:`DataFrame`, or
    when a Timezone-aware :class:`datetime.datetime` is found in an array-like
    of mixed time offsets, and ``utc=False``.

See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_timedelta : Convert argument to timedelta.
convert_dtypes : Convert dtypes.

Notes
-----

Many input types are supported, and lead to different output types:

- **scalars** can be int, float, str, datetime object (from stdlib :mod:`datetime`
  module or :mod:`numpy`). They are converted to :class:`Timestamp` when
  possible, otherwise they are converted to :class:`datetime.datetime`.
  None/NaN/null scalars are converted to :const:`NaT`.

- **array-like** can contain int, float, str, datetime objects. They are
  converted to :class:`DatetimeIndex` when possible, otherwise they are
  converted to :class:`Index` with :class:`object` dtype, containing
  :class:`datetime.datetime`. None/NaN/null entries are converted to
  :const:`NaT` in both cases.

- **Series** are converted to :class:`Series` with :class:`datetime64`
  dtype when possible, otherwise they are converted to :class:`Series` with
  :class:`object` dtype, containing :class:`datetime.datetime`. None/NaN/null
  entries are converted to :const:`NaT` in both cases.

- **DataFrame/dict-like** are converted to :class:`Series` with
  :class:`datetime64` dtype. For each row a datetime is created from assembling
  the various dataframe columns. Column keys can be common abbreviations
  like ['year', 'month', 'day', 'minute', 'second', 'ms', 'us', 'ns']) or
  plurals of the same.

The following causes are responsible for :class:`datetime.datetime` objects
being returned (possibly inside an :class:`Index` or a :class:`Series` with
:class:`object` dtype) instead of a proper pandas designated type
(:class:`Timestamp`, :class:`DatetimeIndex` or :class:`Series`
with :class:`datetime64` dtype):

- when any input element is before :const:`Timestamp.min` or after
  :const:`Timestamp.max`, see `timestamp limitations
  <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
  #timeseries-timestamp-limits>`_.

- when ``utc=False`` (default) and the input is an array-like or
  :class:`Series` containing mixed naive/aware datetime, or aware with mixed
  time offsets. Note that this happens in the (quite frequent) situation when
  the timezone has a daylight savings policy. In that case you may wish to
  use ``utc=True``.

Examples
--------

**Handling various input formats**

Assembling a datetime from multiple columns of a :class:`DataFrame`. The keys
can be common abbreviations like ['year', 'month', 'day', 'minute', 'second',
'ms', 'us', 'ns']) or plurals of the same

>>> df = pd.DataFrame({'year': [2015, 2016],
...                    'month': [2, 3],
...                    'day': [4, 5]})
>>> pd.to_datetime(df)
0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

Using a unix epoch time

>>> pd.to_datetime(1490195805, unit='s')
Timestamp('2017-03-22 15:16:45')
>>> pd.to_datetime(1490195805433502912, unit='ns')
Timestamp('2017-03-22 15:16:45.433502912')

.. warning:: For float arg, precision rounding might happen. To prevent
    unexpected behavior use a fixed-width exact type.

Using a non-unix epoch origin

>>> pd.to_datetime([1, 2, 3], unit='D',
...                origin=pd.Timestamp('1960-01-01'))
DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'],
              dtype='datetime64[ns]', freq=None)

**Differences with strptime behavior**

:const:`"%f"` will parse all the way up to nanoseconds.

>>> pd.to_datetime('2018-10-26 12:00:00.0000000011',
...                format='%Y-%m-%d %H:%M:%S.%f')
Timestamp('2018-10-26 12:00:00.000000001')

**Non-convertible date/times**

Passing ``errors='coerce'`` will force an out-of-bounds date to :const:`NaT`,
in addition to forcing non-dates (or non-parseable dates) to :const:`NaT`.

>>> pd.to_datetime('13000101', format='%Y%m%d', errors='coerce')
NaT

.. _to_datetime_tz_examples:

**Timezones and time offsets**

The default behaviour (``utc=False``) is as follows:

- Timezone-naive inputs are converted to timezone-naive :class:`DatetimeIndex`:

>>> pd.to_datetime(['2018-10-26 12:00:00', '2018-10-26 13:00:15'])
DatetimeIndex(['2018-10-26 12:00:00', '2018-10-26 13:00:15'],
              dtype='datetime64[ns]', freq=None)

- Timezone-aware inputs *with constant time offset* are converted to
  timezone-aware :class:`DatetimeIndex`:

>>> pd.to_datetime(['2018-10-26 12:00 -0500', '2018-10-26 13:00 -0500'])
DatetimeIndex(['2018-10-26 12:00:00-05:00', '2018-10-26 13:00:00-05:00'],
              dtype='datetime64[ns, UTC-05:00]', freq=None)

- However, timezone-aware inputs *with mixed time offsets* (for example
  issued from a timezone with daylight savings, such as Europe/Paris)
  are **not successfully converted** to a :class:`DatetimeIndex`.
  Parsing datetimes with mixed time zones will show a warning unless
  `utc=True`. If you specify `utc=False` the warning below will be shown
  and a simple :class:`Index` containing :class:`datetime.datetime`
  objects will be returned:

>>> pd.to_datetime(['2020-10-25 02:00 +0200',
...                 '2020-10-25 04:00 +0100'])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-10-25 02:00:00+02:00, 2020-10-25 04:00:00+01:00],
      dtype='object')

- A mix of timezone-aware and timezone-naive inputs is also converted to
  a simple :class:`Index` containing :class:`datetime.datetime` objects:

>>> from datetime import datetime
>>> pd.to_datetime(["2020-01-01 01:00:00-01:00",
...                 datetime(2020, 1, 1, 3, 0)])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-01-01 01:00:00-01:00, 2020-01-01 03:00:00], dtype='object')

|

Setting ``utc=True`` solves most of the above issues:

- Timezone-naive inputs are *localized* as UTC

>>> pd.to_datetime(['2018-10-26 12:00', '2018-10-26 13:00'], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2018-10-26 13:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

- Timezone-aware inputs are *converted* to UTC (the output represents the
  exact same datetime, but viewed from the UTC time offset `+00:00`).

>>> pd.to_datetime(['2018-10-26 12:00 -0530', '2018-10-26 12:00 -0500'],
...                utc=True)
DatetimeIndex(['2018-10-26 17:30:00+00:00', '2018-10-26 17:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

- Inputs can contain both string or datetime, the above
  rules still apply

>>> pd.to_datetime(['2018-10-26 12:00', datetime(2020, 1, 1, 18)], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2020-01-01 18:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
File:      ~/Documents/data-propressing-reports/.env/lib/python3.10/site-packages/pandas/core/tools/datetimes.py
Type:      function

### Time Deltas

DateTimes are precise times to which a data can be assigned. Another
concept of time on which Pandas is based are the Time Deltas, that are the
measurements of time durations, that is, the time interval between two
precise instants (DateTime). This concept is also fundamental to working
with times and dates in a data analysis.
Pandas implements this concept through `Timedelta`, a class very similar to
the one present in the datetime module of the standard library. This class
also has its own constructor, and the definition of a time interval can be
very simple and intuitive. For example, if we wanted to define the duration
of a time equivalent to one day, it would be enough to write the following:

In [19]:
pd.Timedelta('1 Day')

Timedelta('1 days 00:00:00')

In this case, if we wanted to update a Datetime value, for example, by
increasing its value by an hour, it would be enough to create a Timedelta
value equivalent to an hour and add it to the Datetime variable, thus,
obtaining the updated value. It is, therefore, possible to perform arithmetic
calculations with times using Datetime and Timedelta together, as shown
as follows

In [20]:
df1 = pd.Timestamp('2021-Nov-16 10:30AM')
df1

Timestamp('2021-11-16 10:30:00')

In [21]:
plus_1= pd.Timedelta('1 DAY')
plus_1

Timedelta('1 days 00:00:00')

In [22]:
df2 = plus_1 + df1

df2

Timestamp('2021-11-17 10:30:00')

Another, more formal way of defining time intervals is to enter the relative
amount and unit of time. For example, another way to define a day and time
is to enter 1 as a numeric value, and use the optional unit parameter
defining ‘d’ to define days as a unit of time, as shown as follows:

In [23]:
pd.Timedelta(1, unit="W")

Timedelta('7 days 00:00:00')

Using smaller time units such as seconds, the manufacturer will convert
them to the larger time units, thus, converting them to the corresponding
values of days, hours, and minutes, as shown as follows:

In [24]:
pd.Timedelta(1000, unit="h")

Timedelta('41 days 16:00:00')

In [25]:
pd.Timedelta(31*10, unit="D")  +pd.Timedelta('2 min')

Timedelta('310 days 00:02:00')

In [26]:
pd.Timedelta('31 Days 2 min')

Timedelta('31 days 00:02:00')

There are also more complex ways to define time intervals, which are
useful when you have multiple units together, such as days, minutes, and
hours, as shown as follows:

In [27]:
pd.Timedelta('3D 5:34:23')

Timedelta('3 days 05:34:23')

We have seen that Timedelta defines time intervals and are useful for
performing arithmetic calculations on Timestamp objects. This concept is
even more explicit when we consider the following example:

In [28]:
ts2 = pd.Timestamp('1975-Mar-01 11:30AM')
ts3 = pd.Timestamp('2023-Oct-05 12:00PM')

df3 = ts3 - ts2
df3

Timedelta('17750 days 00:30:00')

In [30]:
ts2 = pd.Timestamp('1960-Jan-01 00:00AM')
ts3 = pd.Timestamp('2023-01-02 15:43')
df3 = ts3 - ts2
df3

Timedelta('23012 days 15:43:00')

As we can see from the result, even by making the difference between two
Timestamps, an object of type `Timedelta` is automatically generated as a
result, without using the constructor.

There is also a data conversion function for Timedelta, called
`to_timedelta()`. In this case, however, parsing is less flexible than
to_datetime. In fact, there is no optional format parameter, and only the
default formats that work with the constructor are recognized, as shown as
follows:

In [31]:
ts4 = pd.Series(['00:22:33','00:13:12','00:24:14'])
ts4

0    00:22:33
1    00:13:12
2    00:24:14
dtype: object

In [32]:
ts5 = pd.to_timedelta(ts4, errors='raise')
ts5

0   0 days 00:22:33
1   0 days 00:13:12
2   0 days 00:24:14
dtype: timedelta64[ns]

### Creating Arrays of Time Values

Now that we have seen what *Timestamps* is  in Pandas, let’s
take a further step – seeing how it is possible to generate an array of this
type of values in a simple and automatic way.
For this purpose, there is the `data_range()` function which allows us to create a predetermined number of values, starting from a given date `(Timestamp)`, and then defining an appropriate time interval, generating a
series of Datetime values all uniformly staggered.

For example, it is possible to generate an array of 10 consecutive days
starting from a specific date (passed as the first argument) defining as
optional parameters `freq = 'D'`, to define the duration of 1 day from one
value to another and, with periods, the number of values to generate. In this
case, the number of consecutive days are 10, as shown as follows:

In [33]:
pd.date_range('2021/11/02', freq='30min', periods=10)

DatetimeIndex(['2021-11-02 00:00:00', '2021-11-02 00:30:00',
               '2021-11-02 01:00:00', '2021-11-02 01:30:00',
               '2021-11-02 02:00:00', '2021-11-02 02:30:00',
               '2021-11-02 03:00:00', '2021-11-02 03:30:00',
               '2021-11-02 04:00:00', '2021-11-02 04:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [34]:
course_breaks = pd.DataFrame(pd.date_range('2024/09/24', freq='30min', periods=10))
course_breaks

                    0
0 2024-09-24 00:00:00
1 2024-09-24 00:30:00
2 2024-09-24 01:00:00
3 2024-09-24 01:30:00
4 2024-09-24 02:00:00
5 2024-09-24 02:30:00
6 2024-09-24 03:00:00
7 2024-09-24 03:30:00
8 2024-09-24 04:00:00
9 2024-09-24 04:30:00

In [38]:
pd.date_range('2023/11/02', freq='177D', periods=10)

DatetimeIndex(['2023-11-02', '2024-04-27', '2024-10-21', '2025-04-16',
               '2025-10-10', '2026-04-05', '2026-09-29', '2027-03-25',
               '2027-09-18', '2028-03-13'],
              dtype='datetime64[ns]', freq='177D')

In [39]:
pd.Timestamp.today()

Timestamp('2025-11-05 10:24:31.423604')

In [40]:
pd.Timestamp.today()

Timestamp('2025-11-05 10:24:35.372521')

In [ ]:
pd.date_range('2023/11/02' , freq='D' , periods=1).day_name()[0]

Index(['Thursday'], dtype='object')

In [44]:
pd.date_range('2023/11/02', freq='177D', periods=10).day_name()

Index(['Thursday', 'Saturday', 'Monday', 'Wednesday', 'Friday', 'Sunday',
       'Tuesday', 'Thursday', 'Saturday', 'Monday'],
      dtype='object')

In [ ]:
pd.date_range('2021/01/01', freq='1234D', periods=10).day_name()

As we can see, the `date_range()` function creates a DatetimeIndex object
containing 10 consecutive days starting from `1st January 2021`.
Another possibility is to pass two different Timestamps, one starting and
one ending, as arguments to the `data_range()` function. The default
intervals are one day, as shown as follows:

In [ ]:
pd.date_range("2021/01/01", "2021/01/10" , freq='3D')

If, on the other hand, we want a staggered time interval with different times,
we must explicitly specify it with the freq parameter. Or we could decide to
subdivide this interval by a certain number of parts; in this case, we will use
the optional parameter, periods.
For example, we would like to create a Timestamp array with 5 minutes
difference within the specified time limits, then we will specify `5T` to
indicate `5 minutes` to the optional freq parameter, as shown as follows:

In [ ]:
pd.date_range("2021/01/01 8:00","2021/01/01 10:00", freq='5t')

Or we might want to divide this time interval into 10 equal parts, each
delimited by a Timestamp. In this case, 10 is assigned to the optional
parameter periods, as shown as follows:

In [ ]:
pd.date_range("2021/01/01 8:00","2021/01/01 10:00", periods=100)

In all these cases, we have seen the generation of an object of type
`DatetimeIndex` containing a list of Datetime values. In many cases, this
kind of object is useful for building Series or DataFrame. For example, it is
quite common to use these values as Index, both in a Series and in a
DataFrame, as shown as follows:

In [ ]:
np.random.randint(21 , 30, 10)

In [ ]:
range_ = pd.date_range("2021/01/01 8:00","2021/01/01 10:00", periods=10)
range_

In [ ]:
np.random.randn(4)

In [ ]:
depart = pd.Timestamp.today() 
range_ = pd.date_range(depart,  freq='1h' , periods=10)
range_

In [ ]:
temp =  np.random.randint(23, 30, 10)
temp

In [ ]:
patient_A =  pd.DataFrame(pd.Series(temp, index=range_))
patient_A

In [ ]:
range_ = pd.date_range("2021/01/01 8:00","2021/01/01 10:00", periods=10)

tsi = pd.Series(np.random.randn(len(range_)), index=range_)
pd.DataFrame(tsi)

But they can also be used to populate their values automatically, as shown
as follows:

In [ ]:
ts5 = pd.Series(range_)
ts5

In the first case, the use of index with datetime64 type values allows you to
easily select rows relating to a particular time interval, as shown as follows:

In [ ]:
tsi["2021/01/01 8:00":"2021/01/01 8:30"]

># <font color=#800080>Task 1:</font> <a class="anchor" id="Task-1"></a>

Black Friday is a big shopping day all over the world. It is on the last Friday of November, but some stores start their Black Friday sales on the last Monday of November and continue until the third Saturday of December. On Black Friday, stores offer big discounts and deals, and shoppers can find great deals on all sorts of items.

Mamadou Sekou owns a small grocery store in Bouake, Ivory Coast. He is wondering why some of his customers complained that he didn't offer any discounts during the holiday season last year. He wants to do better this year, so he has asked you to help him understand his sales data from last year's Black Friday period (BFP).

You have been given a CSV file called `SekouShop_sales.csv` that contains the store's sales data from **November 1st, 2022** to **December 31st, 2022.**

Mamadou Sekou is seeking answers to the following questions:

1. Where does the term "Black Friday" come from? Any idea?


2. Re-arrange the data into two sub-seasons: the blackfriday season (BFS) and normal sales (NSS) season. What are the cumulated sales for each of the sub-seasons.


3. Mamadou Sekou told you that there were days when the store was closed. Looking at the data, can you list those days for each sub-season? What percentage of the actual sub-season do they represent? What percentage of the entire holiday season do those days represent?


4. Fridays are often said to be on average the best sales days for the store. Can you check whether this is true for SekouShop?

5. According to the analysts from other shop owers in the city, as get to the end of the year,  wednesday and tuesdays sales tend to be aligned as people like to shop on those days. Is that true?

># <font color=#800080>Task 2:</font> <a class="anchor" id="Task-1"></a>

Mamadou wants to create schedules and calendars to keep track of important things like restocking, utility bills, and special sales for the upcoming year 2023.

1. `SekouShop` restocks certain perishable items every 3 days. They want you to create a restocking schedule for the next three months (January, February, and March 2023) to help them manage their inventory.

2. `SekouShop` pays its utility bills on the first day of every month. The manager wants you to create reminders five days before each due date for the upcoming year to avoid late fees.

3. `SekouShop` is planning on having special sales every two weeks. Can you create a calendar for all of their event dates for the upcoming year?