<h1 style="text-align: center;"><a title="Data Prep-AIMS-Cmr-2024-25">Quiz 4, Data Prep, AIMS Sen25 </h1>

**Instructor:** 

* Rockefeller

### LEKOUNDA NGOLO Mardochet Gedeon
##

# Travailler avec les Données Temporelles

## 1. Convertissez la chaîne de date suivante `"2024#12#25"` en utilisant `pd.to_datetime()` avec le paramètre de format approprié.

In [3]:
import pandas as pd

In [4]:
pd.to_datetime('2024#25#12' , 
               format = '%Y#%d#%m' )

Timestamp('2024-12-25 00:00:00')

## 2. Convertissez la chaîne `"December-25-2024"` en `pandas Timestamp` en utilisant la spécification de format correcte.

In [ ]:
pd.Timestamp('December-25-2024')

Timestamp('2025-12-25 00:00:00')

In [ ]:
pd.Timestamp('2025 December 25'  ) # ou encore Option 2 (pd.Timestamp est flexible)

Timestamp('2024-12-25 00:00:00')

## 3. Exécutez la commande ci-dessous pour générer un dataframe

In [29]:
import numpy as np
my_initial_df = pd.DataFrame({'year': list(np.random.randint(2000,2025,10)), 
                   'month': list(np.random.randint(1,13,10)), 
                   'day': list(np.random.randint(1,29,10)), 
                   'hour': list(np.random.randint(0,24,10)), 
                   'meal_menu': ['mafe', 'yassa', 'cebon', 'soup', 'mafe', 'grilled fish', 'grilled fish', 'yassa', 'cebon', 'soup']})
my_initial_df['date'] = pd.to_datetime(my_initial_df[['year', 'month', 'day', 'hour']])

my_initial_df = my_initial_df.drop(columns=['year', 'month', 'day', 'hour'])
my_initial_df = my_initial_df[['date', 'meal_menu']].unique()
my_initial_df

AttributeError: 'DataFrame' object has no attribute 'unique'

## Utilisez .unique() pour afficher tous les menus de repas distincts qui sont listés dans le dataframe

In [8]:
my_initial_df['meal_menu'].unique()

array(['mafe', 'yassa', 'cebon', 'soup', 'grilled fish'], dtype=object)

## 4. À quelle(s) date(s) ont-ils cuisiné le repas nommé `'grilled fish'`? 
Écrivez le code pour cela.

In [10]:
date_meal  = my_initial_df[ my_initial_df['meal_menu']=='grilled fish' ]
date_meal

                 date     meal_menu
5 2001-06-15 08:00:00  grilled fish
6 2015-10-08 00:00:00  grilled fish

## 5. À quel(s) nom(s) de jour cela correspond-il exactement? 
(Indice : vous pouvez utiliser `data_frame['column_name'].dt.day_name()`)

In [11]:
date_meal  = my_initial_df[ my_initial_df['meal_menu']=='grilled fish' ]
date_meal['date'].dt.day_name()

5      Friday
6    Thursday
Name: date, dtype: object


## Supposons que vous ayez la date suivante à analyser : `'2025 KEUR 12***04'`. Exécutez le code ci-dessous

In [12]:
saly_date_coerce = pd.to_datetime('2025 KEUR 12***04', format='%Y KEUR %m--%d',
                   errors='coerce')
saly_date_coerce

NaT

In [ ]:
"""
A la sortie nous remarque NaT qui signifie : pas de valeur assignée

"""


## 6. Nous avons passé `ignore` comme paramètre. Décrivez ce qui se passe exactement?

In [13]:
saly_date_ignore = pd.to_datetime('2025 KEUR 12***04', format='%Y KEUR %m--%d',
                   errors='ignore')
saly_date_ignore

/tmp/ipykernel_155609/2780511070.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  saly_date_ignore = pd.to_datetime('2025 KEUR 12***04', format='%Y KEUR %m--%d',

'2025 KEUR 12***04'

In [ ]:
"""
nous remarquons une erreur , une exception a été lévé
et ipykernel (le kernel) nous averti que l'argument 'ignore' est deprecier, et ne sera plus utilise dans les prochaines versions
"""

## 7. Nous avons passé `raise` comme paramètre. Décrivez ce qui se passe exactement?

In [14]:
saly_date_raise = pd.to_datetime('2025 KEUR 12***04', format='%Y KEUR %m--%d',
                   errors='raise')
saly_date_raise

ValueError: time data "2025 KEUR 12***04" doesn't match format "%Y KEUR %m--%d", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
""" 
Une exception de type 'valueError' a ete lévé.
cela est du a une erreur de value entré par rapport  a la valeur attendue par le programme

"""

## 8. Fournissez le format approprié pour résoudre le problème.

In [16]:
saly_date = pd.to_datetime('2025 KEUR 12***04', 
                           format = '%Y KEUR %d***%m')
saly_date

Timestamp('2025-04-12 00:00:00')

## 9. Créez un objet Timedelta représentant : `5 jours, 3 heures et 30 minutes` et ajoutez-y `deux semaines 10 minutes`.

In [26]:
def_1 = pd.Timedelta('5 Day 3hour 30min ')
def_1

Timedelta('5 days 03:30:00')

In [ ]:
def_2 = pd.Timedelta(2, unit="W") + pd.Timedelta(10, unit="min")

total = def_2 + def_1 

total

Timedelta('19 days 03:40:00')



## 10. Générez une plage de dates commençant le `'2025-11-05'` avec une période de tous les 4 jours jusqu'au `30 décembre 2025`.

In [24]:
day_delays = pd.DataFrame(pd.date_range("2025/11/05", "2025/12/30" , freq='4D'))
day_delays

            0
0  2025-11-05
1  2025-11-09
2  2025-11-13
3  2025-11-17
4  2025-11-21
5  2025-11-25
6  2025-11-29
7  2025-12-03
8  2025-12-07
9  2025-12-11
10 2025-12-15
11 2025-12-19
12 2025-12-23
13 2025-12-27